package com.assignment.logger;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Component;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;
import java.util.Map;

/**
 * Parses the JSON conversation log and extracts the assistant responses
 * for each iteration into a readable Markdown report skeleton.
 *
 * Run this manually after the main agent finishes:
 *   java -cp ... com.assignment.logger.ReportExtractor <path-to-log.json>
 */
@Component
public class ReportExtractor {

    private final ObjectMapper mapper = new ObjectMapper();

    public void extractToMarkdown(String jsonLogPath) {
        File jsonFile = new File(jsonLogPath);
        if (!jsonFile.exists()) {
            System.err.println("Log file not found: " + jsonLogPath);
            return;
        }

        try {
            Map<String, Object> root = mapper.readValue(jsonFile,
                    new TypeReference<>() {});

            @SuppressWarnings("unchecked")
            List<Map<String, Object>> messages =
                    (List<Map<String, Object>>) root.get("messages");

            String outputPath = jsonLogPath.replace(".json", "-report.md");
            try (PrintWriter writer = new PrintWriter(new FileWriter(outputPath))) {
                writeReportHeader(writer, root);
                writeInteractionCostTable(writer, root, messages);
                writeAddOutputs(writer, messages);
                writer.println("\n---\n*Generated by ReportExtractor*");
            }

            System.out.println("[REPORT] Markdown skeleton saved: " + outputPath);

        } catch (IOException e) {
            System.err.println("[ERROR] Failed to extract report: " + e.getMessage());
        }
    }

    private void writeReportHeader(PrintWriter w, Map<String, Object> root) {
        w.println("# Software Architecture (2026) — Assignment 2 Report");
        w.println();
        w.println("**AI Paradigm:** " + root.getOrDefault("ai_paradigm", "Single-Agent"));
        w.println("**LLM Used:** " + root.getOrDefault("llm", "gpt-5.4"));
        w.println("**Session Start:** " + root.getOrDefault("session_start", ""));
        w.println("**Session End:** " + root.getOrDefault("session_end", ""));
        w.println();
        w.println("---");
        w.println();
    }

    private void writeInteractionCostTable(PrintWriter w,
                                            Map<String, Object> root,
                                            List<Map<String, Object>> messages) {
        long userTurns = messages.stream()
                .filter(m -> "user".equals(m.get("role"))).count();

        w.println("## II. Interaction Cost Analysis");
        w.println();
        w.println("| Metric | Value |");
        w.println("|--------|-------|");
        w.println("| Way of completing | Single-Agent (Option 2) |");
        w.println("| LLM used | " + root.getOrDefault("llm", "gpt-5.4") + " |");
        w.println("| Number of human interactions (turns) | " + userTurns + " |");
        w.println("| Prompt tokens | " + tokenValue(root, "prompt_tokens") + " |");
        w.println("| Completion tokens | " + tokenValue(root, "completion_tokens") + " |");
        w.println("| Total token consumption (K tokens) | " + kTokenValue(root) + " |");
        w.println("| Time cost (min) | *fill in* |");
        w.println();
        w.println("---");
        w.println();
    }

    @SuppressWarnings("unchecked")
    private String tokenValue(Map<String, Object> root, String key) {
        Object tokenUsage = root.get("token_usage");
        if (!(tokenUsage instanceof Map<?, ?> usage)) {
            return "Not recorded";
        }
        Object value = ((Map<String, Object>) usage).get(key);
        return value == null ? "Not recorded" : value.toString();
    }

    @SuppressWarnings("unchecked")
    private String kTokenValue(Map<String, Object> root) {
        Object tokenUsage = root.get("token_usage");
        if (!(tokenUsage instanceof Map<?, ?> usage)) {
            return "Not recorded";
        }
        Object value = ((Map<String, Object>) usage).get("total_k_tokens");
        if (value instanceof Number number) {
            return String.format("%.3f", number.doubleValue());
        }
        return value == null ? "Not recorded" : value.toString();
    }

    private void writeAddOutputs(PrintWriter w, List<Map<String, Object>> messages) {
        w.println("## I. Output Results of ADD");
        w.println();

        // Step 1
        messages.stream()
                .filter(m -> "assistant".equals(m.get("role"))
                        && Integer.valueOf(0).equals(m.get("iteration")))
                .findFirst()
                .ifPresent(m -> {
                    w.println("### ADD Step 1: Review Inputs");
                    w.println();
                    w.println((String) m.get("content"));
                    w.println();
                    w.println("---");
                    w.println();
                });

        // Iterations 1-4
        String[] iterationTitles = {
            "Iteration 1: Establishing an Overall System Structure",
            "Iteration 2: Identifying Structures to Support Primary Functionality",
            "Iteration 3: Addressing Reliability and Availability Quality Attributes",
            "Iteration 4: Addressing Development and Operations"
        };

        for (int i = 1; i <= 4; i++) {
            final int iter = i;
            w.println("### " + iterationTitles[i - 1]);
            w.println();

            messages.stream()
                    .filter(m -> "assistant".equals(m.get("role"))
                            && Integer.valueOf(iter).equals(m.get("iteration")))
                    .findFirst()
                    .ifPresent(m -> {
                        w.println("**Timestamp:** " + m.get("timestamp"));
                        w.println();
                        w.println((String) m.get("content"));
                    });

            w.println();
            w.println("---");
            w.println();
        }
    }
}
